name: criticality-analysis
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - affine=2.4.0
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - cftime=1.6.5
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - contextily=1.7.0
  - contourpy=1.3.3
  - cycler=0.12.1
  - double-conversion=3.4.0
  - fiona=1.10.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - gdal=3.12.1
  - geographiclib=2.1
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geopy=2.4.1
  - geos=3.14.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - jinja2=3.1.6
  - joblib=1.5.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - lerc=4.0.0
  - libaec=1.1.5
  - libarchive=3.8.5
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.8
  - libcurl=8.18.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.12.1
  - libglib=2.86.3
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnetcdf=4.9.3
  - libpng=1.6.54
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mercantile=1.2.1
  - minizip=4.0.10
  - mkl=2025.3.0
  - munkres=1.1.4
  - muparser=2.3.5
  - netcdf4=1.7.4
  - networkx=3.6.1
  - numpy=2.4.1
  - openjpeg=2.5.4
  - openssl=3.6.1
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.47
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - proj=9.7.1
  - pthread-stubs=0.4
  - pyogrio=0.12.1
  - pyparsing=3.3.1
  - pyproj=3.7.2
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.10.1
  - rasterio=1.4.4
  - requests=2.32.5
  - scikit-learn=1.8.0
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.2
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.4
  - tqdm=4.67.1
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - anywidget==0.9.21
      - arro3-compute==0.6.5
      - arro3-core==0.6.5
      - arro3-io==0.6.5
      - cartopy==0.25.0
      - damagescanner==0.9b14
      - et-xmlfile==2.0.0
      - exactextract==0.3.0
      - geoarrow-rust-core==0.6.1
      - geohexgrid==3.0.0
      - igraph==1.0.0
      - ipywidgets==8.1.8
      - jupyterlab-widgets==3.0.16
      - lonboard==0.13.0
      - openpyxl==3.1.5
      - osm-flex==1.1.1
      - psygnal==0.15.1
      - pyarrow==22.0.0
      - pyshp==3.0.3
      - pyyaml==6.0.3
      - rasterstats==0.20.0
      - rioxarray==0.19.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - simplejson==3.20.2
      - texttable==1.7.0
      - widgetsnbextension==4.0.15
      - xarray==2025.12.0
